### ISSUE TITLE
How to enable globally in nginx.conf

### ISSUE THREAD

**Issue by stefanpejcic** [denysvitali/nginx-error-pages#11]
Hi, instead of doing:
> Then add to each of your vhosts the following:
> 
> include snippets/error_pages.conf;

Cant we just enable it globally once for all domains *(every .conf file inside /etc/nginx/sites-enabled/)?

**Comment by stefanpejcic** [comment]
because custom error messages are not applied to domains pointed to the ip but not added to nginx:

![2023-12-07_12-40](https://github.com/denysvitali/nginx-error-pages/assets/6408320/79f42633-f730-421e-8fd9-8b4d046a0ebb)

**Comment by reatlat** [comment]
@stefanpejcic you should be able to create a partial config file for your config and import it for any domains
Try to check snippets from repo

**Comment by parkr** [comment]
I believe you could add this to the `http` section in your `nginx.conf`. I believe the error_page directive can be used there.
