### ISSUE TITLE
regex is correct?

### ISSUE THREAD

**Issue by reatlat** [denysvitali/nginx-error-pages#2]
https://github.com/denysvitali/nginx-error-pages/blob/0cdc4e3b4cc824079f74dba7c48f157b5dfc8f73/snippets/error_pages.conf#L34

Are you sure about this rule?

**Comment by reatlat** [comment]
I think should be 

```
location ~ /4[0125][0-9].html
```
or
```
location ~ /4[0-9][0-9].html
```

**Comment by denysvitali** [comment]
You're right! I missed the 2 !  
  
I'm still thinking what's best:
`4[0125][0-9].html` or `4[0-9]{2}.html`  
  
Generally speaking, since we're binding a location on a webserver, the stricter we are the better.  
I think I'll go with the first one then. What are your thoughts about it?

**Comment by reatlat** [comment]
@denysvitali yep, I think first way better, actually on my server I made `4[0125][0-9].html`
TY for so cool and simple templates, exactly what I want =)

**Comment by denysvitali** [comment]
Thank you for opening the issue! I'll close it as soon as I get to a PC and commit the changes :+1:
