### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by reatlat** [denysvitali/nginx-error-pages#3]
https://github.com/denysvitali/nginx-error-pages/blob/cdc898cb5dccb6f1f7a5b0a4e9908e3eaf89ed40/_errors/main.css#L1

Hey man,
Why you have this css here???

just copy paste from another project?

is it short version of normalize???

**Comment by denysvitali** [comment]
It's my minified [thebestmotherfuckingwebsite](https://github.com/denysvitali/thebestmotherfuckingwebsite) CSS ;)
