### ISSUE TITLE
typo in HTTP 507 error page

### ISSUE THREAD

**Issue by ghost** [denysvitali/nginx-error-pages#4]
The status for the HTTP 507 error page seems incorrect :

https://github.com/denysvitali/nginx-error-pages/blob/e2b965da83f719833cfcd5ae0e5c7d7faaeae589/507.html#L20

it should be Insufficient Storage instead of Bad Gateway

http://webconcepts.info/concepts/http-status-code/507

**Comment by denysvitali** [comment]
Thank you! I'll fix it ASAP.

**Comment by denysvitali** [comment]
Fixed. I'm now using an API to automatically generate the error codes and descriptions.
