### ISSUE TITLE
Duplicate MIME type

### ISSUE THREAD

**Issue by re-thc** [denysvitali/nginx-error-pages#6]
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/snippets/error_pages.conf:11

**Comment by denysvitali** [comment]
Thanks for the issue, actually @CapacitorSet already spotted this issue in one of our production servers and fixed it, but I forgot to merge the changes here.
I see there is a PR (#8) that was made to address this issue. I think I'll merge that one and close this issue :+1:
