### ISSUE TITLE
Redirects won't work

### ISSUE THREAD

**Issue by shadowlord017** [denysvitali/nginx-error-pages#7]
If backend uses redirects (301, 302 etc) it will be broken

**Comment by denysvitali** [comment]
Yes, my bad. 30x status codes aren't errors, therefore they shouldn't be handled by NGINX error pages. I'll fix this ASAP

**Comment by denysvitali** [comment]
Seems to be fixed now. Can you check and report back?

**Comment by shadowlord017** [comment]
Yes, this works

**Comment by denysvitali** [comment]
Perfect! Thanks for your feedback!
